### ISSUE TITLE
Firmware update documentation not very clear

### ISSUE THREAD

**Issue by fguiet** [LowPowerLab/CurrentRanger#14]
Hi,

I am not reporting a firmware issue here, I just want to mention that the firmware update documentation could be improved.
I found some parts not very obvious to me.

The firmware update documentation can be found here : <https://lowpowerlab.com/guide/currentranger/programming-firmware-updates/>

This part for instance:

> To access the UF2 bootloader, double tap on the RST button

I have got the `Current ranger R3` and I can tell that you will not find any RST button ! 

After some times, I discovered that there were a tiny label RST on the bottom side of the silkscreen.

Next to that label, one can found 4 plots in the PCB...this were the button should go...

So if you want to go in bootloader mode, you have to use a dupont wire to short 2 plots (in order to reproduce the button action).

Moreover, how can I update my bootloader? It seems that my `current ranger R3` had not been shipped with this new bootloader as it does not appear as a flash drive on Windows 10 Family...

Maybe I have to check this link : <https://github.com/microsoft/uf2-samdx1>

My two cents,
Fred

**Comment by LowPowerLab** [comment]
Thanks, I added an INFO paragraph in the [programming page](https://lowpowerlab.com/guide/currentranger/programming-firmware-updates/) to clarify this and the reason why there is no RST button on older units.
