### ISSUE TITLE
Question about the BT check (R3)

### ISSUE THREAD

**Issue by mrWheel** [LowPowerLab/CurrentRanger#15]
@LowPowerLab 

Can you please explain this code:
```
#ifdef BT_SERIAL_EN
  //BT check
  Serial.print("Bluetooth AT check @");Serial.print(SERIAL_UART_BAUD);Serial.print("baud...");
  SerialBT.begin(SERIAL_UART_BAUD);
  SerialBT.print("AT"); //assuming HC-06, no line ending required
  uint32_t timer=millis();
  while(millis()-timer<1000) //about 1s to respond
  {
    if (SerialBT.available()==2 && SerialBT.read()=='O' && SerialBT.read()=='K')
    {
      BT_found=true;
      break;
    }
  }

  Serial.print(BT_found?"OK!":"No HC-06 response.\r\nChecking for BT v3.0...");

  if (!BT_found)
  {
    SerialBT.print("\r\n"); //assuming HC-06 version 3.0 that requires line ending
    uint32_t timer=millis();
    while(millis()-timer<50) //about 50ms to respond
    {
      if (SerialBT.available()==4 && SerialBT.read()=='O' && SerialBT.read()=='K' && SerialBT.read()=='\r' && SerialBT.read() == '\n')
      {
        BT_found=true;
        break;
      }
    }
  
    Serial.println(BT_found?"OK!":"No response.");
  }

  BT_LOGGING_ENABLED = BT_found;
 ```
It is my understanding that the BT device has to be put in "AT-mode" which it normally is not.
So how does the above code block work? I don't think it will ever replay with "OK" being it with or without "\r\n"..

**Comment by LowPowerLab** [comment]
The code is pretty self explanatory. It looks for a specific device to respond to an ascii AT command, to confirm its presence or not.

Unfortunately these modules seem to come in all kinds of variants and firmware revisions. They use AT commands to change their settings. If the one you have does not, you will need to find one that does, or modify the firmware to make it work with yours. I would recommend USB logging instead.

I added some details on the [bluetooth/logging page](https://lowpowerlab.com/guide/currentranger/bluetooth-data-logging/) to help clarify some details about this.
