### ISSUE TITLE
BT and OLED ....? (R3)

### ISSUE THREAD

**Issue by mrWheel** [LowPowerLab/CurrentRanger#16]
Hi,

according to this code blok:
```
#ifdef BT_SERIAL_EN
  if (BT_LOGGING_ENABLED) {
    if (OLED_found) {
      u8g2.setFont(u8g2_font_siji_t_6x10); //https://github.com/olikraus/u8g2/wiki/fntgrpsiji
      u8g2.drawGlyph(104, 10, 0xE00B); //BT icon
    }
   .
   .
```
.. it should be possible to have BT logging and the OLED screen at the same time .. but the connector for BT is not exposed when the OLED screen is in place.
Am I missing something?

**Comment by LowPowerLab** [comment]
More questions in the forum please.
