### ISSUE TITLE
Serial.begin() missing in CurrentRanger_R3.ino?

### ISSUE THREAD

**Issue by anupamvarghese** [LowPowerLab/CurrentRanger#17]
Can't seem to find Serial.begin(SERIALBAUD) in the R3 sketch. That's perhaps the reason why there is no Serial output and no response to ?+ENTER either?

**Comment by LowPowerLab** [comment]
There is no Serial.begin(), it is not needed.
Only UART serial has a begin (`SerialBT.begin()`).

**Comment by anupamvarghese** [comment]
My mistake, was trying Termite serial viewer, had to give Flow Control: RTS/CTS instead of NONE to get the serial to work.
