### ISSUE TITLE
Fusion file for CR_OLED?

### ISSUE THREAD

**Issue by cmidgley** [LowPowerLab/CurrentRanger#18]
Any chance you have a Fusion 360 file for `CR_OLED.stl`?  My LCD screens are about 2mm too wide, and adjusting the overall box size makes it sloppy holding on to the socket.  It would be nice to just adjust the outer box without affecting the socket dimensions.

**Comment by LowPowerLab** [comment]
Unfortunately I do not have a fusion file. This was designed by the [same person that made the CurrentViewer](https://github.com/MGX3D/CurrentViewer) and he has published his OLED case design [here](https://www.thingiverse.com/thing:4588111/files).

He has now allowed me to publish the SCAD file in this repo.
