### ISSUE TITLE
Question regarding OLED

### ISSUE THREAD

**Issue by helmar74** [LowPowerLab/CurrentRanger#19]
Hi everyone,

sorry for bothering you.
I have a current ranger with oled running.
The OLED shows the following:
![image](https://user-images.githubusercontent.com/25499089/156400225-06c435ef-bbb6-4479-8b01-f80acd05aedc.png)

So my simple Question is:
What does the values in the upper left corner mean?
AUTO is clear for me, as I selected auto range mode.
But what does the values 1/2 and 124 mean?

Thank you in advance

**Comment by LowPowerLab** [comment]
This place is for creating issues, the forum is where questions should be places, this question was already answered there.
https://lowpowerlab.com/forum/currentranger/screen-info-on-the-oled/msg29231/#msg29231

**Comment by helmar74** [comment]
Hi sorry,
I asked in the forum. 
But the shortcuts in the answer don't say me anything:
`The 1/2 means the CR is using half ADC reference where possible (ex in the lower range) for increased resolution of readings. The other number is the ADC reading.`
