### ISSUE TITLE
Can't get an SD card recognized on the SPI pins (R3)

### ISSUE THREAD

**Issue by rmptxf** [LowPowerLab/CurrentRanger#20]
CS pin was set to 3 on the Arduino sketch. We even tried PIN_PA09 and SS too, with no success.
We're looking to record the current measurements into the SD card.
This is the board we're using:
![R3_bottom](https://user-images.githubusercontent.com/65089074/221237863-984420ae-9c31-4bf6-a238-53242115b755.jpg)

**Comment by LowPowerLab** [comment]
So how can I help?
Maybe show me the SD board in question and how you connect it to the CR?
Otherwise this is a non CR related problem and issue will be closed, topic is more appropriate in [the forum](https://lowpowerlab.com/forum/currentranger/).

**Comment by rmptxf** [comment]
Hi, we've just gotten it up an running now. It was a voltage issue rather than a pin number. The CS is indeed **PIN_PA09**.
Thank you
