### ISSUE TITLE
Log Function

### ISSUE THREAD

**Issue by catalinalb** [LowPowerLab/CurrentRanger#21]
Hello,

Could someone explain or point me to a link where I can find info about how can I log the data on PC? 
I do have the Bluetooth device, but over usb would be also ok in this step (I do have an isolator for USB A)

Is there a plotter for windows or linux? Hopefully I don´t need to change the firmware...

Thank you,
Catalin Alb

**Comment by LowPowerLab** [comment]
https://lowpowerlab.com/guide/currentranger/bluetooth-data-logging/
